### ISSUE TITLE
Connection refused error

### ISSUE THREAD

**Issue by soorya-sankar-s** [shantanukhond/YT-Assets#1]
I can configure, start & log in to the superset app. But, getting this error after logging in.
![image](https://github.com/shantanukhond/YT-Assets/assets/159917828/1d5f3d86-235c-4031-8f49-c8c921f48c4f)

`

/app/superset/superset_env/lib/python3.11/site-packages/flask_limiter/extension.py:337: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
  warnings.warn(
[2024-03-31 20:40:06 +0000] [1059] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:40:06 +0000] [1059] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:40:06 +0000] [1059] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:40:06 +0000] [1059] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:40:06 +0000] [1059] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:40:07 +0000] [1059] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:40:07 +0000] [1059] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:40:07 +0000] [1059] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:40:08 +0000] [1059] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:40:08 +0000] [1059] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:40:08 +0000] [1059] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:40:08 +0000] [1059] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:40:08 +0000] [1068] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:40:08 +0000] [1064] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:40:08 +0000] [1064] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:40:08 +0000] [1059] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:40:08 +0000] [1059] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:40:08 +0000] [1068] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:40:09 +0000] [1068] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:40:09 +0000] [1068] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:40:09 +0000] [1068] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:40:09 +0000] [1068] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:40:09 +0000] [1068] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:40:10 +0000] [1068] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:40:11 +0000] [1068] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:40:11 +0000] [1068] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:41:11 +0000] [1067] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:41:14 +0000] [1063] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:41:14 +0000] [1063] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:41:14 +0000] [1066] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:41:14 +0000] [1065] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:41:14 +0000] [1065] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:41:14 +0000] [1063] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:41:14 +0000] [1066] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:41:14 +0000] [1065] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:41:14 +0000] [1065] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:41:14 +0000] [1068] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:41:14 +0000] [1063] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:41:14 +0000] [1067] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:41:14 +0000] [1067] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:41:14 +0000] [1066] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:41:14 +0000] [1066] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:41:14 +0000] [1067] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:41:15 +0000] [1067] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:41:15 +0000] [1067] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:41:15 +0000] [1067] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:41:15 +0000] [1067] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:41:15 +0000] [1067] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:41:15 +0000] [1067] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:45:17 +0000] [1066] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-03-31 20:45:17 +0000] [1066] [WARNING] Error sending message to statsd
Traceback (most recent call last):
  File "/app/superset/superset_env/lib/python3.11/site-packages/gunicorn/instrument/statsd.py", line 131, in _sock_send
    self.sock.send(msg)
ConnectionRefusedError: [Errno 111] Connection refused`

**Comment by shantanukhond** [comment]
Can you check if you are able to connect database externally? I guess database refusing to connect.

**Comment by soorya-sankar-s** [comment]
which database?
and please let me know how to check that.

**Comment by shantanukhond** [comment]
Actually these are warnings I am not able to see any error. This connection refused warnings we also got but those did not affect any of functionality. Can you once verify the memory of server if it is more than 4GB?

**Comment by shantanukhond** [comment]
Lets connect over some other medium so that it will be easy for both of us to resolve issue.
